2025-05-21 19:38:34,676 [ERROR] Tkinter callback exception
Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "c:\Users\chris\Documents\energy_neural_system\main.py", line 1098, in <lambda>
    drawwin.ws_canvas.bind('<Configure>', lambda e: update_draw_window(drawwin.ws_canvas, drawwin.ws_image_id, drawwin.metrics_label))
                                                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: update_draw_window() missing 1 required positional argument: 'metrics_label'
2025-05-21 19:40:00,897 [ERROR] Tkinter callback exception
Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "c:\Users\chris\Documents\energy_neural_system\main.py", line 1098, in <lambda>
    drawwin.ws_canvas.bind('<Configure>', lambda e: update_draw_window(drawwin.ws_canvas, drawwin.ws_image_id, drawwin.metrics_label))
                                                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: update_draw_window() missing 1 required positional argument: 'metrics_label'
